### ISSUE TITLE
JDK 8u72

### ISSUE THREAD

**Issue by vbsessa** [tuxjdk/tuxjdk#15]
Any news on JDK 8u72 (.deb, .rpm, .tar.gz staticly build)?

**Comment by TheIndifferent** [comment]
Hopefully will have time to get to it this week, will create both static build and and rpms.

**Comment by AnwarShah** [comment]
Any plan to release for 32-bit Ubuntu? I'm on 14.04

**Comment by vbsessa** [comment]
Any news on this?
It's been quite some time. :-(

**Comment by TheIndifferent** [comment]
Sorry for the delay, trying to fix some issues before refreshing patches for the newer version.

**Comment by TheIndifferent** [comment]
Ok, may take me more time to fix all the things I want fixed, so for now just refreshing for 8u92:
https://github.com/tuxjdk/tuxjdk/releases/tag/8.92.03

**Comment by TheIndifferent** [comment]
Packages for RPM-based distributions will appear here:
http://download.opensuse.org/repositories/home:/tuxjdk/
