### ISSUE TITLE
Why did this fixes are not on OpenJDK

### ISSUE THREAD

**Issue by mageddo** [tuxjdk/tuxjdk#16]
@TheIndifferent Why did Oracle not add  this fixes that you have done on they build, You know?

**Comment by TheIndifferent** [comment]
Number of reasons.
* this set of patches is one-man show, and the implementation is not the best. Would be great to have some more developers working on this feature.
* those changes to font renderer are using fontconfig, which, as far as I know, available only on linux, while freetypeScaler is supposed to be cross-platform implementation.
* there is a number of corner-cases not covered by those patches, for example headless image printing server with fontconfig configured for LCD rendering.

After NetBeans will start supporting OpenJDK 9, I will try to reimplement those patches in better way, but for now this simple and dirty implementation should be enough for IDEs to work.
