### ISSUE TITLE
Provide tar package download

### ISSUE THREAD

**Issue by machak** [tuxjdk/tuxjdk#6]
I just extract package and create symlink or define it in startup script of java (desktop app)
...this is easier than installing & struggling with default JDK on your system. 
For time being I'll try to build package myself

**Comment by TheIndifferent** [comment]
Tar packages were provided previously, but I was not able to build it so statically so the Fedora 22 build would work properly on CentOS 6 for example, so moved to building for every distro separately. If you know how to do such static build - please share.

To address the issue you're talking about, [the tuxjdk repos](http://download.opensuse.org/repositories/home:/tuxjdk/) are containing tuxjdk-launchers package, which adds launch scripts into /usr/local/bin, which in turn should be earlier in path then default /usr/bin location.

**Comment by TheIndifferent** [comment]
Here is an attempt to produce a static build, could you please try it and report if it works on your system?
https://googledrive.com/host/0B68yuEpDuq6waUl5UjNTUWRlYTQ/tuxjdk-8.66.03.tar.xz

**Comment by machak** [comment]
works fine on: 
4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linu

**Comment by TheIndifferent** [comment]
Great! Thanx for the report. Appeared to be simpler than I thought originally.

At the moment I'm facing the issue that I cannot clone through NetBeans, some issue with missing certificates, will try to fix that ASAP, but don't be surprised.
