### ISSUE TITLE
Ubuntu?

### ISSUE THREAD

**Issue by rahilwazir** [tuxjdk/tuxjdk#7]
There is no `.tar.xz` file, how can I install it for Ubuntu?

**Comment by TheIndifferent** [comment]
Yea, ubuntu packaging is hugely different from RPM and I haven't had any time to learn it, and no one is willing to contribute a simple script-invoking descriptors. Hopefully I will have time for that in following month or two, but no promises. I will leave the issue opened for now.

In the meantime, building your own package should not be complicated, just needs compile-time dependencies, the guide is written in main readme file. Next week I will be able to install ubuntu 15.10 myself and write more detailed instructions for that.

**Comment by vdudouyt** [comment]
By the way, I have recently tried to build on Ubuntu and found that even after applying all patches, the fonts are looking in exactly the same way as in OpenJDK. But the binary packages found somewhere across the internets were working fine.

**Comment by TheIndifferent** [comment]
That is strange. Thanx for reporting that, next week I will update tuxjdk to 8.66.03 and will check what's going on with ubuntu, and maybe will share binary packages for 15.10.

**Comment by vdudouyt** [comment]
Please don't forget to include the debian/ specifications in this repository after you do that. So that everybody could easily build it on Debian-based systems.

Thanks

**Comment by TheIndifferent** [comment]
That will take me way more time, I'm not familiar with deb packages at all. But I will write a step-by-step guideline how to install all dependencies and build binaries on Ubuntu 15.10, maybe someone will be able to contribute deb sources faster than I will get to it.

**Comment by rahilwazir** [comment]
Sorry I may not know, but `jdk-8u25-tuxjdk-b01.tar.xz` is available in `.tar.xz`
Why it now becomes difficult to build for Debian?

**Comment by TheIndifferent** [comment]
I was building 8u25 on openSUSE 12.3, which just happened to work on some other distributions. At the moment I am not able to build a package for example on Fedora 22 and make it work on CentOS 6.

Of course if anyone would be able to instruct me how to build openjdk with fully statical linking against everything and the binaries from Fedora 22 will work on older systems - I'm all for it, and tar.gz binary packages will be available.

**Comment by kshchepanovskyi** [comment]
Trying to build tuxjdk on Ubuntu 15.10.

There are few issues with `HGTAG='jdk8u51-b16'`.

By some reason one of patches failed (update in openjdk?), here is fix:

```diff
diff --git a/quilt-patches/tuxjdk/add-fontconfig-support.diff b/quilt-patches/tuxjdk/add-fontconfig-support.diff
index f8d0ed1..f57875f 100644
--- a/quilt-patches/tuxjdk/add-fontconfig-support.diff
+++ b/quilt-patches/tuxjdk/add-fontconfig-support.diff
@@ -2,14 +2,14 @@ Index: jdk8u60/jdk/make/lib/Awt2dLibraries.gmk
 ===================================================================
 --- jdk8u60.orig/jdk/make/lib/Awt2dLibraries.gmk
 +++ jdk8u60/jdk/make/lib/Awt2dLibraries.gmk
-@@ -824,7 +824,7 @@ $(eval $(call SetupNativeCompilation,BUI
+@@ -826,7 +826,7 @@ $(eval $(call SetupNativeCompilation,BUI
      LDFLAGS := $(subst -Xlinker -z -Xlinker defs,,$(LDFLAGS_JDKLIB)) $(LDFLAGS_CXX_JDK) \
          $(call SET_SHARED_LIBRARY_ORIGIN), \
      LDFLAGS_SUFFIX := $(BUILD_LIBFONTMANAGER_FONTLIB), \
 -    LDFLAGS_SUFFIX_linux := -lawt $(LIBM) $(LIBCXX) -ljava -ljvm -lc, \
 +    LDFLAGS_SUFFIX_linux := -lawt $(LIBM) $(LIBCXX) -ljava -ljvm -lc -lfontconfig, \
-     LDFLAGS_SUFFIX_solaris := -lawt -lawt_headless -lc $(LIBM) $(LIBCXX) -ljava -ljvm, \
-     LDFLAGS_SUFFIX_aix := -lawt -lawt_headless $(LIBM) $(LIBCXX) -ljava -ljvm,\
+     LDFLAGS_SUFFIX_solaris := -lawt -lawt_xawt -lc $(LIBM) $(LIBCXX) -ljava -ljvm, \
+     LDFLAGS_SUFFIX_aix := -lawt -lawt_xawt $(LIBM) $(LIBCXX) -ljava -ljvm,\
      LDFLAGS_SUFFIX_macosx := -lawt $(LIBM) $(LIBCXX) -undefined dynamic_lookup \
 Index: jdk8u60/jdk/src/share/native/sun/font/freetypeScaler.c
 ===================================================================
```

Also build fail due to "This OS is not supported" - to fix this change hotspot/make/linux/Makefile

```
-SUPPORTED_OS_VERSION = 2.4% 2.5% 2.6% 2.7% 3%
+SUPPORTED_OS_VERSION = 2.4% 2.5% 2.6% 2.7% 3% 4%
```

**Comment by kshchepanovskyi** [comment]
Also, you have to install libfontconfig1-dev, otherwise build will fail on compilation stage:

```
sudo apt-get install fontconfig libfontconfig1-dev
```

**Comment by kshchepanovskyi** [comment]
Results of my experiment on Ubuntu 15.10:

* **font issue is solved**, fonts in the IntelliJ IDEA 15 become a lot better.
* but there is some issue with jvm - it eat all available memory (30Gb with swap) and then crashed

![image](https://cloud.githubusercontent.com/assets/4040120/10921382/ed69b5f2-827d-11e5-820a-61a992fae3ee.png)

**Comment by kshchepanovskyi** [comment]
I will try to make a package too, maybe on this weekend.

**Comment by kshchepanovskyi** [comment]
Hm, looks like openjdk package on ubuntu already contains a lot of patches: http://bazaar.launchpad.net/~openjdk/openjdk/openjdk8/files/head:/debian/patches/

**Comment by rahilwazir** [comment]
@kshchepanovskyi Can you please write down the steps?

**Comment by kshchepanovskyi** [comment]
@rahilwazir same steps as in readme, with the only difference that I used `HGTAG='jdk8u60-b27'`.

Dev packages that I install to make things compile:

```bash
sudo apt-get install mercurial
sudo apt-get install quilt
sudo apt-get install libX11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
sudo apt-get install libcups2-dev
sudo apt-get install libfreetype6-dev
sudo apt-get install libasound2-dev
sudo apt-get install fontconfig libfontconfig1-dev
```

After that I used following commands to test result (paths will be different for you):

```bash
export JAVA_HOME=/home/ks/build/build/images/j2re-image/
export JDK_HOME=/home/ks/build/build/images/j2sdk-image/
/opt/idea-IU-143.381.42/bin/idea.sh
```

**Comment by kshchepanovskyi** [comment]
I prepared packages for Ubuntu 15.10:

* http://ksprojects.org/packages/ubuntu/15.10/amd64/tuxjdk-8-jre_8.60-1.deb
* http://ksprojects.org/packages/ubuntu/15.10/amd64/tuxjdk-8-jdk_8.60-1.deb

Do not forget to run following commands after installation:

````
sudo update-alternatives --config java
sudo update-alternatives --config javac
```

P.S. Packages are provided "as-is", you install them on your own risk. I cannot guarantee that everything is working. I'm trying to figure out how to work with PPA - that will be more secure and trusted way for distributing ubuntu packages.

**Comment by kshchepanovskyi** [comment]
Configuration I used to build packages: https://github.com/tuxjdk/tuxjdk/pull/10 

Comments are welcome.

**Comment by kshchepanovskyi** [comment]
UPD: If somebody needs example how it works.

This is how IntelliJ IDEA looks with TuxJDK/JRE (font size is 14):

![image](https://cloud.githubusercontent.com/assets/4040120/10982470/092a01ae-8416-11e5-8c78-ac1f61638707.png)

This is how it looks with default JDK (changed size for all fonts from 14 to 18, otherwise it is too small):

![image](https://cloud.githubusercontent.com/assets/4040120/10982606/d80a1ee6-8416-11e5-9594-0e0c224a009a.png)

With default JDK fonts look weird, lines are too thin + anti-aliasing does not work properly.

**Comment by rahilwazir** [comment]
@kshchepanovskyi Thanks for the packages. But It doesn't work in Ubuntu 15.04 it requires `util-linux >= 2.6` I guess I need to upgrade to 15.10

**Comment by kshchepanovskyi** [comment]
I can try make packages for `Ubuntu 12.04.5 LTS` / `Ubuntu 14.04.1 LTS`, most probably packages for these release will be also compatible with 15.x.

**Comment by rahilwazir** [comment]
@kshchepanovskyi  That would be great!

**Comment by kshchepanovskyi** [comment]
@rahilwazir you can also try https://github.com/achaphiv/ppa-fonts/tree/master/openjdk-fontfix

**Comment by TheIndifferent** [comment]
Here is an attempt to produce a static build, could you all please try it and report back if it works or if there are any problems with it?
https://googledrive.com/host/0B68yuEpDuq6waUl5UjNTUWRlYTQ/tuxjdk-8.66.03.tar.xz

**Comment by rahilwazir** [comment]
@TheIndifferent Its working fine

**Comment by rahilwazir** [comment]
@kshchepanovskyi Great I didn't know that. I'll try that as well

**Comment by p2rkw** [comment]
Works great on Linux Mint with NetBeans 8.1.
```3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by rahilwazir** [comment]
@TheIndifferent Any update, when this will be added to the project?

**Comment by TheIndifferent** [comment]
I found quite serious issue, current tuxjdk fails to build openjdk from source, so that has to be addressed before anything else.

**Comment by TheIndifferent** [comment]
Ok, finally had some time to debug the build and found the problem that openjdk cannot be built if there are no fonts installed. So changed the dockerfile used to produce static build, and created a release, it has tar.xz download as well:
https://github.com/tuxjdk/tuxjdk/releases

And of course please report any issues with that build.

**Comment by rahilwazir** [comment]
@TheIndifferent Thanks working fine for me atleast, will report if I find any issue
